export default {
    ADD_PERSON_TO_CONTACT_LIST: 'ADD_PERSON_TO_CONTACT_LIST',
    REMOVE_PERSON_FROM_CONTACT_LIST: 'REMOVE_PERSON_FROM_CONTACT_LIST',
    MOVE_PERSON_UP_IN_CONTACT_LIST: 'MOVE_PERSON_UP_IN_CONTACT_LIST',
    MOVE_PERSON_DOWN_IN_CONTACT_LIST: 'MOVE_PERSON_DOWN_IN_CONTACT_LIST',
}